[params]
header = "Ingin Membuat Website?<br>Tapi tidak bisa coding. Tenang, serahkan projek anda kepada saya."
github = "https://github.com/alifprihantoro"
gitlab = "https://gitlab.com/alifprihantoro"
facebook = "https://facebook.com/alifprihantoro"
sitename = "MuryP Beta"
twitter = "@alifprihantoro"
og_image = "https://alifprihantoro.gitlab.io/image/noimg.png"
hosting = "/script/"
host = "/img/"
img = "/authors/muryp.png"
thumb = "/authors/muryp.min.png"
icon = "/image/muryp/favicon.ico"
bagianAtas = "https://alifprihantoro.gitlab.io/image/bg.png"
