[[nav]]
identifier = "About"
name = "iabout"
url = "#about"
weight = 1
[[nav]]
identifier = "contact"
name = "tlp"
url = "#contact"
weight = 2
[[nav]]
identifier = "download cv"
name = "idownload"
url = "https://github.com/alifprihantoro/alifprihantoro/raw/master/Alief_Prihantoro_CV_-_Upto_Date_25_Okt_2021.pdf"
weight = 3
[[nav]]
identifier = "portfolio"
name = "ifile"
url = "https://github.com/alifprihantoro/alifprihantoro"
weight = 4
[[nav]]
identifier = "project"
name = "ifile"
url = "#project"
weight = 5
[[nav]]
identifier = "blog"
name = "inote"
url = "/blog"
weight = 6
[[nav]]
identifier = "Catatan"
name = "inote"
url = "/note"
weight = 7

# sosmed muryp -----------------------------
[[sosmed]]
identifier = "fb"
name = "@murypbeta"
url = "facebook.com/murypbeta"
weight = 1
[[sosmed]]
identifier = "ig"
name = "@murypbeta"
url = "instagram.com/murypbeta"
weight = 2
[[sosmed]]
identifier = "tw"
name = "@murypbeta"
url = "twitter.com/murypbeta"
weight = 3
[[sosmed]]
identifier = "yt"
name = "@murypbeta"
url = "youtube.com/channel/UCIxGzpxYCqLqY953v9K05gw"
weight = 4
# sosmed alifprihantoro -----------------------------
[[sosmed2]]
identifier = "fb"
name = "@alifprihantoro"
url = "facebook.com/alifprihantoro"
weight = 1
[[sosmed2]]
identifier = "ig"
name = "@alifprihantoro"
url = "instagram.com/alifprihantoro"
weight = 2
[[sosmed2]]
identifier = "tw"
name = "@alifprihantoro"
url = "twitter.com/alifprihantoro"
weight = 3
[[sosmed2]]
identifier = "git"
name = "@alifprihantoro"
url = "github.com/alifprihantoro"
weight = 4
[[sosmed2]]
identifier = "yt"
name = "@alifprihantoro"
url = "youtube.com/channel/UCbXd_susO9uwjuBxdilCbUw"
weight = 5
[[sosmed2]]
identifier = "ilinkedin"
name = "@alifprihantoro"
url = "https://www.linkedin.com/in/alifprihantoro"
weight = 6

# sosmed alifprihantoro -----------------------------
[[contact]]
identifier = "tlp"
name = "+62 8382 9383 123"
url = "https://wa.me/message/PE5QUV4RBIU6L1"
weight = 1
[[contact]]
identifier = "gmail"
name = "alifmuryp@gmail.com"
url = "mailto:alifmuryp@gmail.com"
weight = 2
[[contact]]
identifier = "telegram"
name = "@muryp"
url = "https://t.me/muryp"
weight = 3
